language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
matrix:
  allow_failures:
    - python "nightly"
  fast_finish: true

install:
  - "pip install -qU --compile pip"
  - "pip install -r requirements.txt"

script:
  - "python setup.py sdist"
  - "pip install ."
  - "make check"
  - "SPHINXOPTS='-n -W' make docs"

after_success:
  - coveralls
