language: python
python:
  - "2.7"
  - "3.3"
matrix:
  fast_finish: true
install:
  - "mv setup.cfg{,.bak}"
  - "pip install -q -r requirements.txt"
  - "pip install -q -r test_crumbs/requirements.txt"
  - "pip install -q flake8 --use-mirrors"
  - "mv setup.cfg{.bak,}"
script:
  - python setup.py build
  - python setup.py install
  - flake8
  - nosetests
